comment: false # Ref: https://docs.codecov.io/docs/pull-request-comments

ignore:
  - '**/*.stories.*'

coverage:
  status:
    project:
      default:
        threshold: 0% # Ref: https://docs.codecov.io/docs/codecovyml-reference#coveragestatus
        target: auto
        informational: true # Don't block PRs

# Since Backstage is a mono repo, flags here help in getting the code coverage of individual packages.
# Documentation: https://docs.codecov.io/docs/flags
flags:
  core:
    paths:
      - packages/core/
    carryforward: true
  core-api:
    paths:
      - packages/core-api/
    carryforward: true
