apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: acme-corp
  description: The acme-corp organization
spec:
  type: organization
  profile:
    displayName: ACME Corp
    email: info@example.com
    picture: https://example.com/logo.jpeg
  children: [infrastructure]
---
apiVersion: backstage.io/v1alpha1
kind: Location
metadata:
  name: example-groups
  description: A collection of all Backstage example Groups
spec:
  targets:
    - ./infrastructure-group.yaml
    - ./boxoffice-group.yaml
    - ./backstage-group.yaml
    - ./team-a-group.yaml
    - ./team-b-group.yaml
    - ./team-c-group.yaml
    - ./team-d-group.yaml
