apiVersion: backstage.io/v1alpha1
kind: Group
metadata:
  name: team-d
  description: Team D
spec:
  type: team
  profile:
    displayName: Team D
    email: team-d@example.com
    picture: https://example.com/groups/team-d.jpeg
  parent: boxoffice
  children: []
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: eva.macdowell
spec:
  profile:
    displayName: Eva MacDowell
    email: eva-macdowell@example.com
    picture: https://example.com/staff/eva.jpeg
  memberOf: [team-d]
---
apiVersion: backstage.io/v1alpha1
kind: User
metadata:
  name: lucy.sheehan
spec:
  profile:
    displayName: Lucy Sheehan
    email: lucy-sheehan@example.com
    picture: https://example.com/staff/lucy.jpeg
  memberOf: [team-d]
