app:
  title: Backstage Tugboat Preview
  baseUrl:
    $env: TUGBOAT_DEFAULT_SERVICE_URL

backend:
  baseUrl:
    $env: TUGBOAT_DEFAULT_SERVICE_URL
  cors:
    origin:
      $env: TUGBOAT_DEFAULT_SERVICE_URL
    methods: [GET, POST, PUT, DELETE]
    credentials: true
